version: '3'
services:
  app:
    image: pcourbin/decidim:0.20.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        decidim_version: 0.20.0
#    volumes:
#      - .:/code
#      - bundle:/usr/local/bundle
#      - node_modules:/code/node_modules
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://decidim:pgpassword@pg/app_development
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=decidim
      - DATABASE_PASSWORD=pgpassword
      - RAILS_ENV=development
#      - RAILS_ENV=production
      - DB_CREATE=true
      - ADMIN_ENABLE=true
      - ADMIN_EMAIL=admin@mydecidim.org
      - ADMIN_PASSWORD=myadminpassword
      - DEFAULT_LOCALE=fr
      - 'DEFAULT_LOCALES_AVAILABLE=[:fr,:en,:es,:de,:it]'
    ports:
      - 3000:3000
    links:
      - pg
  pg:
    image: postgres
    environment:
      - POSTGRES_USER=decidim
      - POSTGRES_PASSWORD=pgpassword

#    volumes:
#      - pg-data:/var/lib/postgresql/data
volumes:
  node_modules: {}
  bundle: {}
  pg-data: {}
