version: '3'
services:
  app:
    image: pcourbin/decidim:0.20.0
    environment:
      - DATABASE_URL=postgres://decidim:pgpassword@pg/app_production
      - RAILS_SERVE_STATIC_FILES=true # If RAILS_ENV=production and you don't have NGINX before requests
      - RAILS_ENV=production
      - DB_CREATE=true
      - ADMIN_ENABLE=true
      - ADMIN_EMAIL=admin@mydecidim.org
      - ADMIN_PASSWORD=myadminpassword
      - DEFAULT_LOCALE=en
      - 'DEFAULT_LOCALES_AVAILABLE=[:en,:fr,:es,:de,:it,:ca]'
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY_BASE=my_secret_key_base
      - SMTP_USERNAME=mymail@gmail.com
      - SMTP_PASSWORD=mypassword
      - SMTP_ADDRESS=smtp.gmail.com
      - SMTP_DOMAIN=gmail.com
    ports:
      - 3000:3000
    links:
      - pg
      - redis
    restart: always

  pg:
    image: postgres
    environment:
      - POSTGRES_USER=decidim
      - POSTGRES_PASSWORD=pgpassword
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis
    volumes:
      - redis-data:/data
    restart: always

volumes:
  pg-data: {}
  redis-data: {}
