version: '3'
services:
  app:
    image: pcourbin/decidim:0.21.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        decidim_version: 0.21.0
#    volumes:
#      - .:/code
#      - bundle:/usr/local/bundle
#      - node_modules:/code/node_modules
    environment:
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=decidim
      - DATABASE_PASSWORD=pgpassword
      - RAILS_ENV=development
      - DB_CREATE=true
      - DB_SEED_DATA=true
      - DEFAULT_LOCALE=en
      - 'DEFAULT_LOCALES_AVAILABLE=[:en,:fr,:es,:de,:it,:ca]'
    ports:
      - 3000:3000
    links:
      - pg

  pg:
    image: postgres
    environment:
      - POSTGRES_USER=decidim
      - POSTGRES_PASSWORD=pgpassword
#    volumes:
#      - pg-data:/var/lib/postgresql/data

volumes:
  node_modules: {}
  bundle: {}
  pg-data: {}
